# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:  黄旺鑫的博客
email: 1101723183@qq.com
description: "博客"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  h1101723183
logo:             logo.png
future: true


# Build settings
markdown: kramdown
theme: jekyll-theme-primer
plugins:
  - jekyll-feed


# Links to include in footer navigation
# For external links add external: true
links:
  - title: 首页
    url: /
    external: false
    icon: home
  - title: 归档
    url: /categories
  - title: 关于我
    url: /about



# 分页
paginate: 5
paginate_path: "page:num"




# Site Source, Change the directory where Jekyll will read files

# source: DIR




# Site Destination, Change the directory where Jekyll will write files

# destination: DIR




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/




# Force inclusion of directories and/or files in the conversion. 
# .htaccess is a good example since dotfiles are excluded by default.

# include:
#  - 




# Keep files
# When clobbering the site destination, keep the selected files. 
# Useful for files that are not generated by jekyll; 
# e.g. files or assets that are generated by your build tool. 
# The paths are relative to the destination.

# keep_files: 
#  -




# Time Zone
# Set the time zone for site generation. 
# This sets the TZ environment variable, which Ruby uses to handle time and date creation and manipulation. 
# Any entry from the IANA Time Zone Database is valid, e.g. America/New_York. 
# A list of all available values can be found here:
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. 
# When serving on a local machine, the default time zone is set by your operating system. 
# But when served on a remote host/server, the default time zone depends on the server's setting or location.
timezone: Asia/Shanghai


# Encoding
encoding: utf-8


# Drafts，是否显示草稿
# show_drafts: false 


# Future, Publish posts or collection documents with a future date.
# future: true

# Unpublished, 标记为未发布的帖子
# unpublished: BOOL

# Incremental build 
# 启用实验增量构建功能。
# 增量构建仅重新构建已更改的帖子和页面，从而显着改善大型网站的性能，但也可能在某些情况下破坏网站生成。
# incremental: BOOL

# Local Server Port， Listen on the given port.
# 本地服务器端口
port: 4001

# Local Server Hostname
# 本地服务器主机名
# host: 127.0.0.1

# 该defaults键包含一组范围/值对，用于定义应为特定文件路径设置哪些默认值，以及可选的文件类型。
# 假设您想要将默认布局添加到网站中的所有页面和帖子中。你可以将它添加到你的_config.yml文件中：
# 在这里，我们正在确定values路径中存在的任何文件scope。
# 由于路径设置为空字符串，因此它将应用于项目中的所有文件。
# 您可能不希望为项目中的每个文件设置布局 
# 例如，像css文件 - 因此您也可以type在该项下指定一个值scope。
# 这只会设置类型为的文件的布局posts。
# 不同类型的提供给你的pages，posts，drafts或在您的网站的任何集合。
# 虽然type是可选的，但您必须为path创建scope/values对时指定一个值。

 # defaults:
 #   -
 #     scope:
 #       path: "" # an empty string here means all files in the project
 #       type: "posts" # previously `post` in Jekyll 2.2.
 #     values:
 #       layout: "default"
